create table
  public.global_inventory (
    id bigint generated by default as identity,
    num_red_ml integer null,
    num_green_ml integer not null default 0,
    num_blue_ml integer not null default 0,
    num_dark_ml integer not null default 0,
    gold integer null,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.potion_inventory (
    id bigint generated by default as identity,
    red smallint not null default '0'::smallint,
    green smallint not null default '0'::smallint,
    blue smallint not null default '0'::smallint,
    dark smallint not null default '0'::smallint,
    quantity bigint not null default '0'::bigint,
    sku text not null,
    price integer not null,
    desired_qty bigint not null,
    constraint potion_inventory_pkey primary key (id),
    constraint potion_inventory_sku_key unique (sku)
  ) tablespace pg_default;

create table
  public.carts (
    id bigint generated by default as identity,
    customer_name text null default ''::text,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_contents (
    id bigint generated by default as identity,
    cart_id bigint not null,
    potion_id bigint not null,
    quantity integer not null default 0,
    constraint cart_transactions_pkey primary key (id),
    constraint cart_contents_cart_id_fkey foreign key (cart_id) references carts (id) on update restrict on delete cascade,
    constraint cart_contents_potion_id_fkey foreign key (potion_id) references potion_inventory (id) on update restrict on delete restrict
  ) tablespace pg_default;

