name: Push Prod Image

on:
  workflow_dispatch:
    inputs:
      docker_push_tag:
        description: 'Tag to push to Dockerhub'
        required: true
        type: string
  push:
    branches:
      - "main"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stellar-elixirs:${{ inputs.docker_push_tag || 'latest' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max